### Send POST request with json body

#  credentials: [
#    'cade.hintz',
#    'cade15@gmail.com',
#    'vipakulomemuxaze',
#    'a amet omnis suscipit'
#  ]


POST http://localhost:4096/authentication/login
Content-Type: application/json

{
  "credentials": ["zelma87", "wuhaporemafezewe"]
}

###
GET http://localhost:4096/sample/sample
Authentication: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2VudElkIjoxNiwic2Vzc2lvbklkIjoyOSwiaWF0IjoxNjU5MzQ1MDk4fQ.umij99oS1m8PianDKg_Z-53GYJ8Kr-NuJYwSDdM44Zo

{
}

###
POST http://localhost:4096/authentication/logout
Content-Type: application/json
Authentication: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2VudElkIjoxNiwic2Vzc2lvbklkIjoyOSwiaWF0IjoxNjU5MzQ1MDk4fQ.umij99oS1m8PianDKg_Z-53GYJ8Kr-NuJYwSDdM44Zo

{
}
