### Send POST request with json body

#  credentials: [
#    'cade.hintz',
#    'cade15@gmail.com',
#    'vipakulomemuxaze',
#    'a amet omnis suscipit'
#  ]


POST http://localhost:4096/authentication/login
Content-Type: application/json

{
  "credentials": ["cade.hintz", "vipakulomemuxaze"]
}
